### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by JamesMarino** [madmod/stalk-my-friends#1]
How were you going about accessing the API endpoints for Find My Friends? Would you know how Apple does authentication etc?

**Comment by madmod** [comment]
I just looked at the requests made on iCloud.com. I think it's broken right now. I will probably have time to fix it in a month or so.

**Comment by varenc** [comment]
it'd be cool to see this get fixed =)

**Comment by madmod** [comment]
It looks like I got this repo mixed up with another one and I didn't realize that this only had filler code. :man_facepalming: I have published the latest version to github and npm. (Version 0.1.2, now with 100% more functionality! 😆 ) It's still a total mess but the cli works. Since the API is almost definitely going to be refactored to work better than my hacked together demo I'd appreciate a PR if someone wants to clean it up a bit before they use it.
